# Documentation: http://docs.travis-ci.com/user/languages/julia/
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
language: julia
matrix:
  include:
    - os: linux
      compiler: "g++-4.9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
      julia: release
    - os: osx
      compiler: "clang"
      julia: nightly
notifications:
  email: true
